# Generated by Django 2.2.3 on 2019-07-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Arabic Word', max_length=200)),
                ('word_diacless', models.CharField(help_text='Arabic Word Diacless', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SeerahTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SeerahQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Topic name', max_length=200)),
                ('answer', models.TextField()),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incubator.SeerahTopic')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(help_text='Unique ID', max_length=200, primary_key=True, serialize=False)),
                ('android_version', models.CharField(blank=True, max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fcm_token', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='App name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incubator.User')),
                ('app_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incubator.App')),
            ],
        ),
        migrations.AddConstraint(
            model_name='applike',
            constraint=models.UniqueConstraint(fields=('app_id', 'uid'), name='App and User are unique together'),
        ),
    ]
