# Generated by Django 2.2.3 on 2019-07-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applike',
            name='App and User are unique together',
        ),
        migrations.RenameField(
            model_name='applike',
            old_name='uid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='applike',
            name='app_id',
        ),
        migrations.AddField(
            model_name='applike',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incubator.App'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(help_text='Unique ID for this particular book across whole library', max_length=200, primary_key=True, serialize=False),
        ),

    ]
