# Generated by Django 2.2.3 on 2019-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0002_auto_20190730_2318'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applike',
            constraint=models.UniqueConstraint(fields=('app', 'user'), name='App and User are unique together'),
        ),
    ]
