# Generated by Django 2.2.3 on 2020-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionid', models.IntegerField(blank=True, db_column='CollectionID', null=True)),
                ('bookid', models.TextField(blank=True, db_column='BookID', null=True)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('nameshort_en', models.TextField(blank=True, null=True)),
                ('hadith_start', models.IntegerField(blank=True, null=True)),
                ('hadith_end', models.IntegerField(blank=True, null=True)),
                ('hadith_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionid', models.IntegerField(blank=True, db_column='CollectionID', null=True)),
                ('bookid', models.TextField(blank=True, db_column='BookID', null=True)),
                ('chapid', models.TextField(blank=True, db_column='ChapID', null=True)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('name_ar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Chapter',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionid', models.AutoField(db_column='CollectionID', primary_key=True, serialize=False)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('global_id', models.TextField(db_column='global', primary_key=True, serialize=False)),
                ('collectionid', models.TextField(blank=True, db_column='CollectionID', null=True)),
                ('bookid', models.TextField(blank=True, db_column='BookID', null=True)),
                ('chapid', models.TextField(blank=True, db_column='ChapID', null=True)),
                ('hadithidcollection', models.TextField(blank=True, db_column='HadithIDCollection', null=True)),
                ('hadithid', models.TextField(blank=True, db_column='HadithID', null=True)),
                ('narrator_en', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('grade_en', models.TextField(blank=True, null=True)),
                ('reference_en', models.TextField(blank=True, null=True)),
                ('related_en', models.TextField(blank=True, null=True)),
                ('narrator_ar', models.TextField(blank=True, null=True)),
                ('text_ar', models.TextField(blank=True, null=True)),
                ('narrator_arend', models.TextField(blank=True, null=True)),
                ('grade_ar', models.TextField(blank=True, null=True)),
                ('narrator_ar_diacless', models.TextField(blank=True, null=True)),
                ('text_ar_diacless', models.TextField(blank=True, null=True)),
                ('narrator_arend_diacless', models.TextField(blank=True, null=True)),
                ('grade_ar_diacless', models.TextField(blank=True, null=True)),
                ('narrators', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hadith',
            },
        ),
        migrations.CreateModel(
            name='HadithNarrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.IntegerField(blank=True, null=True)),
                ('narrator_id', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hadithnarattors',
            },
        ),
        migrations.CreateModel(
            name='RelatedHadiths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id_target', models.IntegerField(db_column='global_id_target')),
                ('global_id_related', models.IntegerField(db_column='global_id_related')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relatedhadiths',
            },
        ),
        migrations.CreateModel(
            name='Scholars',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False, unique=True)),
                ('famousname', models.TextField(blank=True, db_column='famousName', null=True)),
                ('fullname', models.TextField(blank=True, db_column='fullName', null=True)),
                ('othername', models.TextField(blank=True, db_column='otherName', null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.TextField(blank=True, db_column='birthDate', null=True)),
                ('birthcity', models.TextField(blank=True, db_column='birthCity', null=True)),
                ('deathdate', models.TextField(blank=True, db_column='deathDate', null=True)),
                ('deathcity', models.TextField(blank=True, db_column='deathCity', null=True)),
                ('howdied', models.TextField(blank=True, db_column='howDied', null=True)),
                ('livecity', models.TextField(blank=True, db_column='liveCity', null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('mudhab', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('kunya', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Scholars',
            },
        ),
    ]
