# Generated by Django 2.2.3 on 2020-03-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hadith',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hadithnarrators',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='relatedhadiths',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scholars',
            options={'managed': True},
        ),
    ]
