# Generated by Django 3.0.4 on 2020-03-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0002_auto_20200321_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='collectionid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hadith.Collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='name_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='nameshort_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='bookid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hadith.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='collectionid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hadith.Collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name_ar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='bookid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hadith.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hadith',
            name='chapid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hadith.Chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hadith',
            name='collectionid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hadith.Collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hadith',
            name='global_id',
            field=models.TextField(db_column='global_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='grade_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='grade_ar_diacless',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='grade_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='hadithid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='hadithidcollection',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hadithnarrators',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithnarrators',
            name='global_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hadith.Hadith'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hadithnarrators',
            name='narrator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hadith.Scholars'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatedhadiths',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatedhadiths',
            name='global_id_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_id_related', to='hadith.Hadith'),
        ),
        migrations.AlterField(
            model_name='relatedhadiths',
            name='global_id_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_id_target', to='hadith.Hadith'),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='birthcity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='birthdate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='deathcity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='deathdate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='famousname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='fullname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='howdied',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='interests',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='livecity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholars',
            name='othername',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
