# Generated by Django 3.0.4 on 2020-04-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0004_auto_20200411_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='collectionid',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='bookid',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapid',
            new_name='Chap',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='collectionid',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='hadith',
            old_name='bookid',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='hadith',
            old_name='chapid',
            new_name='Chap',
        ),
        migrations.RenameField(
            model_name='hadith',
            old_name='collectionid',
            new_name='Collection',
        ),
    ]
